[build]
  command   = "npm run build && npm run copyfunction"
  functions = "out_functions"
  publish   = "out_publish"

[[redirects]]
  from = "/test/*"
  to = "/.netlify/functions/test"
  status = 200
